baseURL = "https://policia.wiki.br/"
languageCode = "pt-br"
title = "Polícia wiki"
theme = "researcher"
enableEmoji = true
googleAnalytics = "G-CP72BMF0ET"

[params]
  author = "Joubert RedRat"
  description = "Wiki contendo algumas informações interessantes sobre as polícias do Brasil"
  favicon = "assets/favicon/favicon.ico"
  [params.style]
    pageWidth = "1100px"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Sobre"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Brasões, logos e escudos"
    url = "/brasoes-logos-escudos"
    weight = 2
  [[menu.main]]
    name = "Links úteis"
    url = "/links-uteis"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true
